#!/bin/bash
vtysh
conf t
router ospf 
ospf router-id 10.255.255.2
passive-interface default 
no passive-interface tunnel.0 
network 10.255.255.0/30 area 0
network 10.10.10.0/28 area 0
exit 
int gre1
ip ospf network point-to-point
ip ospf authentication message-digest 
ip ospf message-digest-key 1 md5 P@ssw0rd
exit
exit
wr
