#!/bin/bash
sudo apt-get update
sudo update-kernel -y 
sudo apt-get install eepm kernel-headers-6.12 kernel-headers-modules-6.12 wireshark zenmap putty -y 
sudo epmi https://download.estersoft.ru/pub/Korinf/x86_64/ALTLinux/p10/eepm-3*.noarch.rpm
sudo epmp packet-tracer -y
cd /home/admin/Загрузки
chmod a+x VMware-Workstation-Full-17.6.4-24832109.x86_64.bundle
sudo ./VMware-Workstation-Full-17.6.4-24832109.x86_64.bundle
sudo reboot
